(function () {
  "use strict";
  const store = window.EMERGENCY_STORE;
  const ui = window.EMERGENCY_UI || {};
  if (!store) return;
  const esc = ui.escapeHtml || ((value) => String(value ?? "").replace(/[&<>\"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char])));
  const toast = ui.showToast || ((message) => window.alert(message));
  const transitions = { "待确认": ["已确认", "误报关闭"], "已确认": ["处理中"], "处理中": ["待复核", "已升级", "处置失败"], "已升级": ["处理中"], "处置失败": ["处理中"], "待复核": ["已关闭", "处理中"] };
  let events = [];
  function list() { return typeof store.listEvents === "function" ? store.listEvents() : []; }
  function eventById(id) { return list().find((item) => String(item.eventId) === String(id)); }
  function metric(label, value, tone) { return `<article class="emergency-metric"><span class="metric-label">${label}</span><strong class="metric-value ${tone || ""}">${value}</strong></article>`; }
  function renderMetrics() { const all = list(); const root = document.getElementById("eventMetrics"); if (root) root.innerHTML = [metric("待确认", all.filter((item) => item.status === "待确认").length, "danger"), metric("处理中", all.filter((item) => ["已确认", "处理中", "已升级", "处置失败"].includes(item.status)).length, "warning"), metric("待复核", all.filter((item) => item.status === "待复核").length), metric("已关闭", all.filter((item) => ["已关闭", "误报关闭"].includes(item.status)).length, "success")].join(""); }
  function renderTypeOptions() { const select = document.querySelector('[data-event-filter="eventType"]'); if (!select) return; const current = select.value; const types = [...new Set(list().map((item) => item.eventType).filter(Boolean))]; select.innerHTML = `<option value="">全部类型</option>${types.map((type) => `<option value="${esc(type)}">${esc(type)}</option>`).join("")}`; select.value = current; }
  function filtered() { const filter = Object.fromEntries([...document.querySelectorAll("[data-event-filter]")].map((field) => [field.dataset.eventFilter, field.value.trim()])); return list().filter((item) => (!filter.keyword || `${item.eventId} ${item.title}`.includes(filter.keyword)) && (!filter.eventType || item.eventType === filter.eventType) && (!filter.level || item.level === filter.level) && (!filter.status || item.status === filter.status)); }
  function actionMarkup(item) { const choices = transitions[item.status] || []; const firstAction = item.status === "待确认" ? `<button class="table-action" type="button" data-event-action="confirm" data-event-id="${esc(item.eventId)}">确认事件</button>` : choices.length ? `<button class="table-action" type="button" data-event-action="transition" data-event-id="${esc(item.eventId)}" data-next-status="${esc(choices[0])}">${esc(choices[0])}</button>` : ""; return `<button class="table-action" type="button" data-event-action="detail" data-event-id="${esc(item.eventId)}">详情</button>${item.status !== "已关闭" && item.status !== "误报关闭" ? `<button class="table-action" type="button" data-event-action="dispatch" data-event-id="${esc(item.eventId)}">进入调度台</button>` : ""}${firstAction}`; }
  function render() { events = filtered(); const body = document.getElementById("eventBody"); if (!body) return; document.getElementById("eventCount").textContent = events.length; body.innerHTML = events.length ? events.map((item) => `<tr data-event-id="${esc(item.eventId)}"><td><strong>${esc(item.eventId)}</strong></td><td>${esc(item.title || "未命名事件")}</td><td>${esc(item.eventType || "-")}</td><td><span class="status-tag status-${String(item.level || "").toLowerCase()}">${esc(item.level || "-")}</span></td><td>${esc(item.location || item.area || "待定位")}</td><td>${esc(item.source || "人工上报")}</td><td>${ui.renderStatus ? ui.renderStatus(item.status) : `<span class="status-tag">${esc(item.status || "-")}</span>`}</td><td>${esc(item.ownerName || item.handler || "未指派")}</td><td>${esc(item.updatedAt || item.discoveredAt || item.occurrenceTime || "-")}</td><td>${actionMarkup(item)}</td></tr>`).join("") : `<tr><td colspan="10" class="empty-cell">暂无应急事件</td></tr>`; const pager = document.getElementById("eventPagination"); if (pager) pager.innerHTML = `<span>共 ${events.length} 条记录</span><span class="page-item active">1</span>`; }
  function transition(eventId, nextStatus) { const item = eventById(eventId); if (!item || !(transitions[item.status] || []).includes(nextStatus)) { toast("当前状态不支持该操作", "error"); return; } try { const updated = store.transitionEvent ? store.transitionEvent(eventId, nextStatus, { operator: "当前用户" }) : store.saveEvent({ ...item, status: nextStatus }); if (updated?.planId || item.planId) { } toast(`事件已${nextStatus}`); renderMetrics(); render(); } catch (error) { toast(error.message || "状态更新失败", "error"); } }
  function detailBody(item) { const plan = item.planId && typeof store.getPlan === "function" ? store.getPlan(item.planId) : null; const options = transitions[item.status] || []; const timeline = (item.timeline || []).slice().reverse().map((record) => `<li class="timeline-item"><span class="timeline-index"><i class="fa-solid fa-clock"></i></span><div><strong>${esc(record.action || record.type || "事件更新")}</strong><p>${esc(record.time || record.createdAt || "-")} · ${esc(record.operator || "系统")}</p></div></li>`).join(""); return `<section class="detail-section"><div class="detail-grid"><div class="info-item"><span class="info-label">事件编号</span><span class="info-value">${esc(item.eventId)}</span></div><div class="info-item"><span class="info-label">来源</span><span class="info-value">${esc(item.source || "人工上报")}</span></div><div class="info-item"><span class="info-label">事件等级</span><span class="info-value">${esc(item.level || "-")}</span></div><div class="info-item"><span class="info-label">当前状态</span><span class="info-value">${esc(item.status || "-")}</span></div><div class="info-item"><span class="info-label">事件类型</span><span class="info-value">${esc(item.eventType || "-")}</span></div><div class="info-item"><span class="info-label">发生位置</span><span class="info-value">${esc(item.location || "待定位")}</span></div><div class="info-item"><span class="info-label">发生时间</span><span class="info-value">${esc(item.occurrenceTime || item.discoveredAt || "-")}</span></div><div class="info-item"><span class="info-label">关联预案</span><span class="info-value">${esc(plan?.name || item.planId || "未匹配")}</span></div></div><p class="detail-description">${esc(item.description || item.message || "暂无事件描述")}</p></section><section class="detail-section"><div class="card-title-row"><h3 class="detail-title">处置操作</h3><div class="btn-row">${options.map((status) => `<button class="btn ${status === "处置失败" || status === "误报关闭" ? "btn-danger-outline" : "btn-secondary"} btn-sm" type="button" data-detail-transition="${esc(status)}" data-detail-event="${esc(item.eventId)}">${esc(status)}</button>`).join("")}<button class="btn btn-primary btn-sm" type="button" data-detail-dispatch="${esc(item.eventId)}">进入调度台</button></div></div></section><section class="detail-section"><h3 class="detail-title">操作时间线</h3><ol class="step-timeline">${timeline || '<li class="empty-cell">暂无操作记录</li>'}</ol></section>`; }
  function openDetail(item) { if (!item) return; window.openAppDrawer({ title: "应急事件详情", body: detailBody(item), footer: `<button class="btn btn-secondary" data-drawer-close>关闭</button>` }); }
  function openCreate() { window.openAppDrawer({ title: "新建应急事件", body: `<div class="form-grid-2"><label class="form-field form-span-2"><span class="form-label form-required">事件标题</span><input class="form-control" data-event-field="title" placeholder="请输入事件标题"></label><label class="form-field"><span class="form-label">事件类型</span><input class="form-control" data-event-field="eventType" placeholder="如：设备故障"></label><label class="form-field"><span class="form-label">事件等级</span><select class="form-control" data-event-field="level"><option>P2</option><option>P1</option><option>P3</option><option>P4</option></select></label><label class="form-field form-span-2"><span class="form-label">发生位置</span><input class="form-control" data-event-field="location" placeholder="请输入位置"></label><label class="form-field form-span-2"><span class="form-label">事件描述</span><textarea class="form-control textarea" data-event-field="description" placeholder="请输入事件描述"></textarea></label></div>`, footer: `<button class="btn btn-secondary" data-drawer-close>取消</button><button class="btn btn-primary" data-event-drawer-save>保存</button>` }); }
  function saveCreate() { const read = (key) => document.querySelector(`[data-event-field="${key}"]`)?.value.trim() || ""; const title = read("title"); if (!title) { toast("请输入事件标题", "error"); return; } const now = new Date().toISOString().slice(0, 19).replace("T", " "); const event = { eventId: `EVT-${Date.now()}`, title, eventType: read("eventType") || "其他", level: read("level") || "P2", location: read("location") || "待定位", description: read("description"), source: "人工上报", status: "待确认", occurrenceTime: now, discoveredAt: now, timeline: [{ time: now, operator: "当前用户", action: "人工创建事件" }] }; try { store.saveEvent(event); window.closeAppDrawer(); toast("事件已创建"); renderMetrics(); renderTypeOptions(); render(); } catch (error) { toast(error.message || "创建失败", "error"); } }
  function goDispatch(eventId) { const target = `dispatch.html?eventId=${encodeURIComponent(eventId)}`; if (typeof ui.navigate === "function") ui.navigate("dispatch", { eventId }); else window.location.href = target; }
  document.addEventListener("click", (event) => {
    const action = event.target.closest("[data-event-action]"); if (action) { const type = action.dataset.eventAction; if (type === "create") openCreate(); if (type === "detail") openDetail(eventById(action.dataset.eventId)); if (type === "dispatch") goDispatch(action.dataset.eventId); if (type === "confirm") transition(action.dataset.eventId, "已确认"); if (type === "transition") transition(action.dataset.eventId, action.dataset.nextStatus); if (type === "reset") { document.querySelectorAll("[data-event-filter]").forEach((field) => { field.value = ""; }); render(); } if (type === "search") render(); }
    const detailTransition = event.target.closest("[data-detail-transition]"); if (detailTransition) { transition(detailTransition.dataset.detailEvent, detailTransition.dataset.detailTransition); window.closeAppDrawer(); }
    const detailDispatch = event.target.closest("[data-detail-dispatch]"); if (detailDispatch) goDispatch(detailDispatch.dataset.detailDispatch);
    const save = event.target.closest("[data-event-drawer-save]"); if (save) saveCreate();
  });
  renderMetrics(); renderTypeOptions(); render();
  const queryEventId = new URLSearchParams(window.location.search).get("eventId"); if (queryEventId) setTimeout(() => openDetail(eventById(queryEventId)), 0);
})();
