(function () {
  window.APP_MENU = [
    {
      key: "gis",
      label: "GIS一张图",
      icon: "fa-solid fa-map-location-dot",
      href: "../gis/one-map.html",
    },
    {
      key: "project",
      label: "管廊管理",
      icon: "fa-solid fa-building",
      children: [
        { key: "project.manage", label: "项目管理", href: "../project/project-management.html" },
        { key: "project.building", label: "管廊管理", href: "../project/building.html" },
        { key: "project.floor", label: "舱室管理", href: "../project/floor.html" },
        { key: "project.house", label: "区段管理", href: "../project/house.html" },
        { key: "project.pipeline", label: "管线管理", href: "../project/pipeline.html" },
      ],
    },
    {
      key: "device",
      label: "设备管理",
      icon: "fa-solid fa-layer-group",
      children: [
        { key: "device.list", label: "设备管理", href: "../device/list.html" },
        { key: "config.system-type", label: "系统类型", href: "../config/system-type.html" },
        { key: "device.category", label: "设备分类", href: "../device/category.html" },
      ],
    },
    {
      key: "home",
      label: "设备监测",
      icon: "fa-solid fa-gauge-high",
      href: "../home/home.html",
    },
    {
      key: "inspection",
      label: "设备巡检",
      icon: "fa-solid fa-clipboard-check",
      children: [
        { key: "inspection.standard-works", label: "标准作业", href: "../inspection/standard-works.html" },
        { key: "inspection.plans", label: "巡检计划", href: "../inspection/plans.html" },
        { key: "inspection.tasks", label: "巡检任务", href: "../inspection/tasks.html" },
      ],
    },
    {
      key: "smart-monitoring",
      label: "智能监测",
      icon: "fa-solid fa-display",
      hidden: true,
      children: [
        { key: "smart-monitoring.parking", label: "停车记录", href: "../monitoring/parking-record.html", hidden: true },
        { key: "smart-monitoring.pedestrian", label: "人行通行记录", href: "../monitoring/pedestrian-record.html", hidden: true },
        { key: "smart-monitoring.device", label: "设备监测", href: "../monitoring/device-monitor.html", hidden: true },
      ],
    },
    {
      key: "subsystems",
      label: "子系统",
      icon: "fa-solid fa-table-cells",
      hidden: true,
      children: [
        {
          key: "video-monitoring",
          label: "视频监控",
          icon: "fa-solid fa-video",
          children: [
            { key: "video-monitoring.live", label: "实时视频", href: "../monitoring/video-monitor.html" },
            { key: "video-monitoring.replay", label: "录像回放", href: "../monitoring/video-replay.html" },
          ],
        },
        {
          key: "fire-system",
          label: "消防系统",
          icon: "fa-solid fa-fire-flame-curved",
          href: "../monitoring/fire-system.html",
        },
        {
          key: "intrusion-alarm",
          label: "入侵报警系统",
          icon: "fa-solid fa-shield-halved",
          href: "../monitoring/intrusion-alarm.html",
        },
        {
          key: "power-monitoring",
          label: "电力监测系统",
          icon: "fa-solid fa-bolt",
          children: [
            { key: "power-monitoring.overview", label: "运行总览", href: "../monitoring/power-monitoring.html?view=overview" },
            { key: "power-monitoring.devices", label: "设备监控", href: "../monitoring/power-monitoring.html?view=devices" },
            { key: "power-monitoring.events", label: "事件记录", href: "../monitoring/power-monitoring.html?view=events" },
          ],
        },
        {
          key: "environment-monitoring",
          label: "环境监测系统",
          icon: "fa-solid fa-leaf",
          href: "../monitoring/environment-monitor.html",
        },
        {
          key: "electronic-patrol",
          label: "电子巡更",
          icon: "fa-solid fa-route",
          href: "../monitoring/electronic-patrol.html",
        },
        {
          key: "communication-system",
          label: "通信系统",
          icon: "fa-solid fa-phone-volume",
          href: "../communication/communication.html",
        },
        {
          key: "smart-manhole",
          label: "智能井盖",
          icon: "fa-solid fa-road-spikes",
          href: "../monitoring/smart-manholes.html",
        },
        {
          key: "access-control",
          label: "门禁系统",
          icon: "fa-solid fa-id-card-clip",
          href: "../monitoring/access-control.html",
        },
        {
          key: "fire-alarm",
          label: "火灾报警系统",
          icon: "fa-solid fa-fire-flame-curved",
          href: "../monitoring/fire-alarm.html",
        },
      ],
    },
    {
      key: "emergency",
      label: "应急管理",
      icon: "fa-solid fa-truck-medical",
      hidden: true,
      children: [
        { key: "emergency.dispatch", label: "应急调度台", href: "../emergency/dispatch.html" },
        { key: "emergency.events", label: "应急事件", href: "../emergency/events.html" },
        { key: "emergency.plans", label: "应急预案", href: "../emergency/plans.html" },
        { key: "emergency.resources", label: "应急物资", href: "../emergency/resources.html" },
        { key: "emergency.personnel", label: "应急人员", href: "../emergency/personnel.html" },
        { key: "emergency.calls", label: "通话记录", href: "../emergency/calls.html" },
      ],
    },
    {
      key: "safety",
      label: "安全管理",
      icon: "fa-solid fa-shield-halved",
      hidden: true,
      children: [
        { key: "safety.plans", label: "安全预案", href: "../safety/plans.html" },
        { key: "safety.regulations", label: "法规库", href: "../safety/regulations.html" },
      ],
    },
    {
      key: "alarm-center",
      label: "报警中心",
      icon: "fa-solid fa-bell",
      children: [
        { key: "alarm-center.info", label: "报警信息", href: "../alarm-center/alarm-info.html" },
        { key: "alarm-center.rule", label: "报警规则", href: "../alarm-center/alarm-rule.html" },
      ],
    },
    {
      key: "big-data",
      label: "大数据分析",
      icon: "fa-solid fa-chart-line",
      hidden: true,
      children: [
        { key: "big-data.diagnosis", label: "设备诊断", href: "../big-data/device-diagnosis.html" },
        { key: "big-data.warning", label: "异常预警", href: "../big-data/abnormal-warning.html" },
        { key: "big-data.energy", label: "能耗分析", href: "../big-data/energy-analysis.html" },
      ],
    },
    {
      key: "configuration",
      label: "组态系统",
      icon: "fa-solid fa-diagram-project",
      hidden: true,
      href: "../network/configuration.html",
    },
    {
      key: "service-center",
      label: "网络管理平台",
      icon: "fa-solid fa-server",
      hidden: true,
      href: "../service-center/service-center.html",
    },
    {
      key: "data-storage",
      label: "数据存储",
      icon: "fa-solid fa-database",
      hidden: true,
      children: [
        { key: "data-storage.realtime", label: "实时数据", href: "../data-storage/realtime.html" },
        { key: "data-storage.history", label: "历史数据", href: "../data-storage/history.html" },
        { key: "data-storage.archive-config", label: "历史归档配置", href: "../data-storage/archive-config.html" },
      ],
    },
    {
      key: "interface-platform",
      label: "接口管理平台",
      icon: "fa-solid fa-plug-circle-bolt",
      hidden: true,
      children: [
        { key: "interface-platform.south", label: "南向采集", href: "../interface-platform/south.html" },
        { key: "interface-platform.north", label: "北向对接", href: "../interface-platform/north.html" },
      ],
    },
    {
      key: "system",
      label: "系统管理",
      icon: "fa-solid fa-gear",
      hidden: true,
      children: [
        { key: "system.user", label: "用户管理", href: "../system/user.html" },
        { key: "system.role", label: "角色管理", href: "../system/role.html" },
        { key: "system.menu", label: "菜单管理", href: "../system/menu.html" },
        { key: "system.department", label: "部门管理", href: "../system/department.html" },
        { key: "system.post", label: "岗位管理", href: "../system/post.html" },
        { key: "system.dictionary", label: "字典管理", href: "../system/dictionary.html" },
        { key: "system.parameter", label: "参数设置", href: "../system/parameter.html" },
        { key: "system.notice", label: "通知公告", href: "../system/notice.html" },
        {
          key: "system.logs",
          label: "日志管理",
          children: [
            { key: "system.operation-log", label: "操作日志", href: "../system/operation-log.html" },
            { key: "system.login-log", label: "登录日志", href: "../system/login-log.html" },
          ],
        },
      ],
    },
  ];
})();
